// =====================
// SCRIPT.JS FOR CHURCH SITE
// Lights in the World Outreach Ministry
// Handles Welcome Screen & Prophetic Word Logic
// =====================

// ====== Elements ======
const welcomeScreen = document.getElementById('welcomeScreen');
const serviceScreen = document.getElementById('serviceScreen');
const todayServiceBtn = document.getElementById('todayServiceBtn');
const getWordBtn = document.getElementById('getWordBtn');
const propheticWordDiv = document.getElementById('propheticWord');
const wordCountSelect = document.getElementById('wordCount');

// ====== Prophetic Words ======
const propheticWords = [
  "GOD SHALL TURN ALL YOUR SWEAT TO SWEET EXPERIENCES THIS MONTH",
  "ALL YOUR CHALLANGES SHALL CRUMBLE BEFORE YOU THIS MONTH",
  "GOD SHALL SURPRISE YOU WITH HIS BLESSINGS THIS MONTH YOUR BREAKTHROUGH SHALL SHUT THE MOUTH OF YOUR ENEMIES",
  "GOD'S HAND SHALL BE VISIBLE IN EVERY ENDEAVOUR OF YOUR LIFE THIS MONTH",
  "FROM NOW, YOU SHALL GO FORWARD ONLY, NO MORE BACKWARDS IN YOUR LIFE",
  "EVERY STEP YOU TAKE FROM NOW SHALL BE PROFITABLE STEPS",
  "THIS MONTH, GOD SHALL SHOW HIMSELF STRONG AND MIGHTY ON YOUR BEHALF",
  "ALL YOUR LOST HONOUR AND GLORY SHALL BE RESTORED TO YOU THIS MONTH",
  "YOUR DOMINION IN CHRIST SHALL BE RESTORED THIS MONTH",
  "EVERY FORM OF UNGODLINESS IN YOUR LIFE SHALL BE SWALLOWED THIS MONTH",
  "YOU SHALL STAND OUT EVERYWHERE YOU GO THIS MONTH.",
  "YOUR OPPRESSORS SHALL GO INTO CAPTIVITY THIS MONTH",
  "YOUR LONG DETAYED MIRACLE SHALL LOCATE YOU THIS MONTH",
  "GOD SHALL TAKE YOU TO YOUR OWN PLACE OF REST THIS MONTH",
  "ALL YOUR STOLEN JOY AND PEACE SHALL BE RESTORED BACK TO YOU THIS MONTH",
  "WHATEVER THAT WANTS TO DESTROY YOUR LIFE SHALL BE DESTROYED THIS MONTH",
  "GOD SHALL WIPE AWAY ALL YOUR TEARS OF MANY YEARS THIS YEAR",
  "THAT DESOLATE LAND IN YOUR LIFE SHALL BE INHABITED THIS YEAR",
  "HEAVEN WILL OPEN OVER YOU THIS YEAR FOR RAIN OF BLESSING",
  "MEN SHALL WONDER AT YOUR PROGRESS THIS YEAR",
  "YOU WILL BE AN ATTRACTION TO ALL THE PEOPLE AROUND YOU",
  "GREAT PEACE AND JOY SHALL FLOW IN YOUR LIFE THIS MONTH",
  "GOD'S FAVOUR SHALL SURROUND YOU WHEREVER YOU GO",
  "ALL YOUR ENEMIES SHALL SUFFER GREAT DEFEAT FROM NOW.",
  "THIS YEAR GOD SHALL SETTLE YOUR CASE, FOR YOU TO GO AND SETTLE OTHERS",
  "EVERY REPROACH IN YOUR LIFE IS TERMINATED TODAY",
  "THIS YEAR, GOD SHALL MAGNIFY YOU IN THE SIGHT OF ALL YOUR",
  "THIS YEAR, YOU WILL SEE THE MIGHTY ACTS OF GOD",
  "GOD SHALL ROLL AWAY ALL YOUR SHAME AND REPROACH THIS YEAR",
  "THE DIVINE SECRET YOU NEED TO REIGN IN LIFE, GOD SHALL UNFOLD THEM TO YOU THIS MONTH",
  "THIS MONTH, GOOD SHALL COME YOUR WAY",
  "EVIL SHALL NO LONGER BE HEARD IN YOUR LIFE & FAMILY",
  "YOU SHALL ASCEND YOUR GOD-ORDAINED THRONE THIS MONTH",
  "FROM NOW, YOU WILL NOT STRUGGLE AGAIN TO COMMAND GREAT RESULT",
  "GOD WILL MAKE YOU SUPER FRUITFUL IN EVERYTHING YOU DO THIS MONTH",
  "GOD SHALL CONNECT YOU WITH DESTINY HELPERS THIS MONTH",
  "THE FORCES OF LIFE SHALL BOW TO YOU FROM NOW.",
  "FOUR DAYS OF SUFFERING ARE OVER",
  "YOU CAN LONGER BE ENSLAVED",
  "THIS MONTH YOU WILL REIGN IN ALL AREAS OF YOUR LIFE",
  "ALL YOUR MOCKERS SHALL GO INTO TREMBLE THIS MONTH",
  "ANYONE WHO WANTS YOU DEAD SHALL DIE MYSTERIOUSLY THIS YEAR",
  "THE PURPOSE OF GOD FOR YOU SHALL STAND, NO MAN CAN ABORT IT",
  "EVERY CONTROVERSY OVER YOUR KINGSHIP SHALL END THIS MONTH",
  "GOD SHALL TOUCH THE HEARTS OF MEN TO LIFT YOU HIGHER",
  "ALL THAT SAID YOU CAN'T REIGN OVER THEM, SHALL BOW TO YOU THIS MONTH",
  "ALL THAT DESPISED YOU SHALL COME BACK TO HONOUR YOU",
  "WHATEVER GOD HAS SAID CONCERNING YOU THIS YEAR SHALL ALL COME TO PASS",
  "THIS MONTH, GOD SHALL GIVE YOU ALL IT TAKES TO RULE IN THE MIDST OF YOUR ENEMIES",
  "THE WORKS OF YOUR HANDS SHALL PROSPER GREATLY THIS MONTH",
  "SATAN WILL NO LONGER BE YOUR PROBLEM OR CONCERN FROM NOW",
  "YOUR LIGHT SHALL SHINE BRIGHTER THIS MONTH",
  "ANYONE WISHING YOU EVIL SHALL NEVER KNOW PEACE AGAIN",
  "GOD SHALL CRUSH THE DEVIL OF SICKNESS IN YOUR LIFE THIS MONTH",
  "GOD SHALL CLOTHE ALL YOUR TROUBLERS WITH SHAME THIS MONTH",
  "EVERYWHERE YOU GO THIS MONTH, YOU SHALL TAKE CHARGE",
  "YOU SHALL REIGN EVEN IN THE MIDST OF YOUR ENEMIES",
  "YOUR HEART DESIRES FOR 2017 SHALL BE GRANTED YOU EXPRESSLY",
  "THE LIGHT OF GOD SHALL SHINE IN ALL YOUR DARK PLACES THIS MONTH",
  "WHATEVER IS COVERING YOUR GLORY IN CHRIST SHALL BE ROLLED AWAY THIS MONTH.",
  "YOUR FINANCIAL STATUS OR POSITIONS MUST CHANGE THIS YEAR",
  "PEOPLE WILL SEE YOU AND BELIEVE THAT GOD BLESSES PEOPLE",
  "PEOPLE SHALL BE FORCED TO FAVOUR YOU THIS MONTH",
  "THE GRACE OF GOD SHALL BE MULTIPLIED IN YOUR LIFE THIS MONTH",
  "EVERYONE HINDERING YOUR PROGRESS MUST SURRENDER THIS MONTH",
  "YOUR GOD-ORDAINED FREEDOM MUST BE ESTABLISHED THIS MONTH",
  "THIS MONTH, GOD SHALL REPOSITION YOU FOR GREATNESS",
  "THIS MONTH, YOU SHALL GO BEYOND ALL YOUR LIMITATIONS",
  "GOD SHALL NULLIFY EVERY PLAN OF THE WICKED ONE AGAINST YOU.",
  "FROM NOW, YOU WILL ENJOY CONSTANT TRIUMPH OVER YOUR ENEMIES",
  "KINGDOM PROSPERITY SHALL BE YOUR IDENTITY FROM NOW.",
  "GOD SHALL DO A NEW THING IN YOUR LIFE & GIVE YOU A NEW NAME."
];

// ====== Event Listeners ======
todayServiceBtn.addEventListener('click', () => {
  welcomeScreen.classList.add('hidden');
  serviceScreen.classList.remove('hidden');
});

getWordBtn.addEventListener('click', () => {
  const count = parseInt(wordCountSelect.value);
  displayWords(count);
});

// ====== Functions ======
function displayWords(count) {
  let selectedWords = [];
  let usedIndexes = new Set();

  while (selectedWords.length < count) {
    const randomIndex = Math.floor(Math.random() * propheticWords.length);
    if (!usedIndexes.has(randomIndex)) {
      selectedWords.push(propheticWords[randomIndex]);
      usedIndexes.add(randomIndex);
    }
  }

  propheticWordDiv.innerHTML = '';

  selectedWords.forEach((word, index) => {
    const wordEl = document.createElement('p');
    wordEl.textContent = word;
    wordEl.classList.add('word-animate');
    wordEl.style.animationDelay = `${index * 0.2}s`;
    propheticWordDiv.appendChild(wordEl);
  });
}

// ====== Optional Animations ======
// Add subtle fade-in for words
const style = document.createElement('style');
style.innerHTML = `
.word-animate {
  opacity: 0;
  transform: translateY(10px);
  animation: fadeWord 0.5s forwards;
}
@keyframes fadeWord {
  to {
    opacity: 1;
    transform: translateY(0);
  }
}`;
document.head.appendChild(style);